USE [master]
GO

/****** Object:  Database [Portal]    Script Date: 21.04.2015 15:24:24 ******/
CREATE DATABASE [Portal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Portal_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Portal.mdf' , SIZE = 307200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Portal_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Portal_log.ldf' , SIZE = 307200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Portal] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Portal].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Portal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Portal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Portal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Portal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Portal] SET ARITHABORT OFF 
GO

ALTER DATABASE [Portal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Portal] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Portal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Portal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Portal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Portal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Portal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Portal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Portal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Portal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Portal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Portal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Portal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Portal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Portal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Portal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Portal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Portal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Portal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Portal] SET  MULTI_USER 
GO

ALTER DATABASE [Portal] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Portal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Portal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Portal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Portal] SET  READ_WRITE 
GO


