//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UlterSystems.PortalService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UlterSystems.PortalService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon, _UserName_. System Portal has found out that _Date_ you have forgotten to note work end. Inform, please, to the manager when you have finished work this day..
        /// </summary>
        internal static string CENotificationMessage {
            get {
                return ResourceManager.GetString("CENotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon. The user _UserName_ has not closed a working interval _Date_..
        /// </summary>
        internal static string CENotificationMessageAdmin {
            get {
                return ResourceManager.GetString("CENotificationMessageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: you have forgotten to finish work..
        /// </summary>
        internal static string CENotificationSubject {
            get {
                return ResourceManager.GetString("CENotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: the User _UserName_ has forgotten to finish work..
        /// </summary>
        internal static string CENotificationSubjectAdmin {
            get {
                return ResourceManager.GetString("CENotificationSubjectAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with the data bases is initialized..
        /// </summary>
        internal static string DBConnectionInitialized {
            get {
                return ResourceManager.GetString("DBConnectionInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon. This users were not noted yet at (_Date_) in a portal..
        /// </summary>
        internal static string NRAllNotificationMessageAdmin {
            get {
                return ResourceManager.GetString("NRAllNotificationMessageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: The users which was not noted today or yesterday..
        /// </summary>
        internal static string NRAllNotificationSubjectAdmin {
            get {
                return ResourceManager.GetString("NRAllNotificationSubjectAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon. The user _UserName_ was not noted yet today (_Date_) in a portal..
        /// </summary>
        internal static string NRNotificationMessageAdmin {
            get {
                return ResourceManager.GetString("NRNotificationMessageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: Mark at system, please..
        /// </summary>
        internal static string NRNotificationSubject {
            get {
                return ResourceManager.GetString("NRNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: the User _UserName_ was not noted yet..
        /// </summary>
        internal static string NRNotificationSubjectAdmin {
            get {
                return ResourceManager.GetString("NRNotificationSubjectAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon, _UserName_. System Portal has found out that today (_Date_) you were not marked in a portal. Make it, please..
        /// </summary>
        internal static string NRTodayNotificationMessage {
            get {
                return ResourceManager.GetString("NRTodayNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon, _UserName_. System Portal has found out that yesterday (_Date_) you were not marked in a portal..
        /// </summary>
        internal static string NRYesterdayNotificationMessage {
            get {
                return ResourceManager.GetString("NRYesterdayNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At closing of working intervals there was an error..
        /// </summary>
        internal static string ProcErrorCE {
            get {
                return ResourceManager.GetString("ProcErrorCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At mail dispatch there was an error..
        /// </summary>
        internal static string ProcErrorMail {
            get {
                return ResourceManager.GetString("ProcErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At dispatch of notices there was an error..
        /// </summary>
        internal static string ProcErrorNR {
            get {
                return ResourceManager.GetString("ProcErrorNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At dispatch the statistic there was an error..
        /// </summary>
        internal static string ProcErrorStat {
            get {
                return ResourceManager.GetString("ProcErrorStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of closing of working intervals is finished..
        /// </summary>
        internal static string ProcFinishedCE {
            get {
                return ResourceManager.GetString("ProcFinishedCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of removal not attached files is finished..
        /// </summary>
        internal static string ProcFinishedCleanAttachments {
            get {
                return ResourceManager.GetString("ProcFinishedCleanAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of dispatch of mail is finished..
        /// </summary>
        internal static string ProcFinishedMail {
            get {
                return ResourceManager.GetString("ProcFinishedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of the notice of not registered users is finished..
        /// </summary>
        internal static string ProcFinishedNR {
            get {
                return ResourceManager.GetString("ProcFinishedNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of dispatch the statistican is finished..
        /// </summary>
        internal static string ProcFinishedStat {
            get {
                return ResourceManager.GetString("ProcFinishedStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is begun procedure of closing of open working intervals..
        /// </summary>
        internal static string ProcStartedCE {
            get {
                return ResourceManager.GetString("ProcStartedCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is begun procedure of dispatch of mail..
        /// </summary>
        internal static string ProcStartedMail {
            get {
                return ResourceManager.GetString("ProcStartedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is begun procedure of the notice of not registered users..
        /// </summary>
        internal static string ProcStartedNR {
            get {
                return ResourceManager.GetString("ProcStartedNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is begun procedure of dispatch the statistic..
        /// </summary>
        internal static string ProcStartedStat {
            get {
                return ResourceManager.GetString("ProcStartedStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal service is started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal service is stopped..
        /// </summary>
        internal static string ServiceStoped {
            get {
                return ResourceManager.GetString("ServiceStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: User {0} statistic {1}-{2}.
        /// </summary>
        internal static string StatisticsDeliverySubject {
            get {
                return ResourceManager.GetString("StatisticsDeliverySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTAL: Office Statistic {0}-{1}.
        /// </summary>
        internal static string StatisticsDeliverySubjectAdmin {
            get {
                return ResourceManager.GetString("StatisticsDeliverySubjectAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer of the notice on closing of a working interval is created..
        /// </summary>
        internal static string TimerCreatedCE {
            get {
                return ResourceManager.GetString("TimerCreatedCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer of dispatch of mail is created..
        /// </summary>
        internal static string TimerCreatedMail {
            get {
                return ResourceManager.GetString("TimerCreatedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer of the notice of unregistered users is created..
        /// </summary>
        internal static string TimerCreatedNR {
            get {
                return ResourceManager.GetString("TimerCreatedNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer of dispatch of statistics is created..
        /// </summary>
        internal static string TimerCreatedStat {
            get {
                return ResourceManager.GetString("TimerCreatedStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at creation of the timer of the notice on closing of a working interval..
        /// </summary>
        internal static string TimerErrorCE {
            get {
                return ResourceManager.GetString("TimerErrorCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at creation of the timer of the notice of unregistered users. .
        /// </summary>
        internal static string TimerErrorNR {
            get {
                return ResourceManager.GetString("TimerErrorNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating statistic timer.
        /// </summary>
        internal static string TimerErrorStat {
            get {
                return ResourceManager.GetString("TimerErrorStat", resourceCulture);
            }
        }
    }
}
