//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.TestingEntitiesManipulation {
    
    
    public partial class EntitiesManipulationControl {
        
        /// <summary>
        /// EntitiesListIncludedControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Portal.TestingEntitiesManipulation.EntitiesListControl EntitiesListIncludedControl;
        
        /// <summary>
        /// RemoveEntitiesButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button RemoveEntitiesButton;
        
        /// <summary>
        /// AddEntitiesButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddEntitiesButton;
        
        /// <summary>
        /// EntitiesListNotIncludedControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Portal.TestingEntitiesManipulation.EntitiesListControl EntitiesListNotIncludedControl;
    }
}
