//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForumMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForumMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ForumMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured while sending your post. It is possible, that the post you are replying, was deleted by administrator..
        /// </summary>
        internal static string mess11_body {
            get {
                return ResourceManager.GetString("mess11_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: A problem occured while sending your post.
        /// </summary>
        internal static string mess11_title {
            get {
                return ResourceManager.GetString("mess11_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information was saved.&lt;p&gt;Please, go back to the home page &lt;UrlHome&gt;.
        /// </summary>
        internal static string mess13_body {
            get {
                return ResourceManager.GetString("mess13_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data was successfully changed.
        /// </summary>
        internal static string mess13_title {
            get {
                return ResourceManager.GetString("mess13_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To execute &lt;i&gt;all&lt;/i&gt; admin actions on this web site, you should be in administrators group..
        /// </summary>
        internal static string mess1_body {
            get {
                return ResourceManager.GetString("mess1_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: you couldn&apos;t execute admin actions.
        /// </summary>
        internal static string mess1_title {
            get {
                return ResourceManager.GetString("mess1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the security settings you are not allowed to edit this post.&lt;p&gt;If you belive that it is an error - contact web site administrator..
        /// </summary>
        internal static string mess2_body {
            get {
                return ResourceManager.GetString("mess2_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You are not allowed to edit this post..
        /// </summary>
        internal static string mess2_title {
            get {
                return ResourceManager.GetString("mess2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already send post with the same text to that or another forum. Duplicate posts are not allowed.&lt;p&gt;&lt;DuplicatePost&gt;.
        /// </summary>
        internal static string mess4_body {
            get {
                return ResourceManager.GetString("mess4_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You Are Trying to Incert A Duplicate Post.
        /// </summary>
        internal static string mess4_title {
            get {
                return ResourceManager.GetString("mess4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forum is not exists.
        /// </summary>
        internal static string mess6_body {
            get {
                return ResourceManager.GetString("mess6_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown forum.
        /// </summary>
        internal static string mess6_title {
            get {
                return ResourceManager.GetString("mess6_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is not exists. It may be deleted by forum administrator..
        /// </summary>
        internal static string mess9_body {
            get {
                return ResourceManager.GetString("mess9_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown post.
        /// </summary>
        internal static string mess9_title {
            get {
                return ResourceManager.GetString("mess9_title", resourceCulture);
            }
        }
    }
}
