//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.GlobalSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ascx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ascx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalSettings.ascx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow duplicate posts.
        /// </summary>
        internal static string AllowDuplicatePosts_Text {
            get {
                return ResourceManager.GetString("AllowDuplicatePosts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus work minutes.
        /// </summary>
        internal static string BonusWorkMinutes_Text {
            get {
                return ResourceManager.GetString("BonusWorkMinutes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books language.
        /// </summary>
        internal static string BooksLanguage_Text {
            get {
                return ResourceManager.GetString("BooksLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply_Text {
            get {
                return ResourceManager.GetString("btnApply.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default date format.
        /// </summary>
        internal static string DefaultDateFormat_Text {
            get {
                return ResourceManager.GetString("DefaultDateFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default time format.
        /// </summary>
        internal static string DefaultTimeFormat_Text {
            get {
                return ResourceManager.GetString("DefaultTimeFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default work time.
        /// </summary>
        internal static string DefaultWorkTime_Text {
            get {
                return ResourceManager.GetString("DefaultWorkTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download base path.
        /// </summary>
        internal static string DownloadBasePath_Text {
            get {
                return ResourceManager.GetString("DownloadBasePath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        internal static string FileManagerWebServiceURL_Text {
            get {
                return ResourceManager.GetString("FileManagerWebServiceURL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum settings.
        /// </summary>
        internal static string ForumSettings_HeaderText {
            get {
                return ResourceManager.GetString("ForumSettings.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        internal static string lblTitle_Text {
            get {
                return ResourceManager.GetString("lblTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail from-address.
        /// </summary>
        internal static string MailFromAddress_Text {
            get {
                return ResourceManager.GetString("MailFromAddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail message template.
        /// </summary>
        internal static string MailMessageTemplate_Text {
            get {
                return ResourceManager.GetString("MailMessageTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server.
        /// </summary>
        internal static string MailServer_Text {
            get {
                return ResourceManager.GetString("MailServer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail subject.
        /// </summary>
        internal static string MailSubject_Text {
            get {
                return ResourceManager.GetString("MailSubject.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main settings.
        /// </summary>
        internal static string MainSettings_HeaderText {
            get {
                return ResourceManager.GetString("MainSettings.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max lunch time.
        /// </summary>
        internal static string MaxLunchTime_Text {
            get {
                return ResourceManager.GetString("MaxLunchTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News discuss forum ID.
        /// </summary>
        internal static string NewsDiscussForumID_Text {
            get {
                return ResourceManager.GetString("NewsDiscussForumID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office settings.
        /// </summary>
        internal static string OfficeSettings_HeaderText {
            get {
                return ResourceManager.GetString("OfficeSettings.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to transformation file.
        /// </summary>
        internal static string PathToTransformationFile_Text {
            get {
                return ResourceManager.GetString("PathToTransformationFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        internal static string SiteName_Text {
            get {
                return ResourceManager.GetString("SiteName.Text", resourceCulture);
            }
        }
    }
}
