//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewsTape {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsTape() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewsTape", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual news.
        /// </summary>
        internal static string actualNews {
            get {
                return ResourceManager.GetString("actualNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive news.
        /// </summary>
        internal static string archiveNews {
            get {
                return ResourceManager.GetString("archiveNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no actual news..
        /// </summary>
        internal static string EmptyActualNews {
            get {
                return ResourceManager.GetString("EmptyActualNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no news in archive..
        /// </summary>
        internal static string EmptyArchiveNews {
            get {
                return ResourceManager.GetString("EmptyArchiveNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header can&apos;t be empty!.
        /// </summary>
        internal static string emptyHeader {
            get {
                return ResourceManager.GetString("emptyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no news found for your request..
        /// </summary>
        internal static string EmptySearchResults {
            get {
                return ResourceManager.GetString("EmptySearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The news text can&apos;t be empty!.
        /// </summary>
        internal static string emptyText {
            get {
                return ResourceManager.GetString("emptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General news.
        /// </summary>
        internal static string generalNews {
            get {
                return ResourceManager.GetString("generalNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [all].
        /// </summary>
        internal static string liAll {
            get {
                return ResourceManager.GetString("liAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found that would match your request..
        /// </summary>
        internal static string NothingWasFound {
            get {
                return ResourceManager.GetString("NothingWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office news.
        /// </summary>
        internal static string officeNews {
            get {
                return ResourceManager.GetString("officeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        internal static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        internal static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
    }
}
