//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmIt.PortalLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfirmIt.PortalLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string BeginTitle {
            get {
                return ResourceManager.GetString("BeginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send user _UserName_ office statistics..
        /// </summary>
        internal static string CanNotSendOfficeStat {
            get {
                return ResourceManager.GetString("CanNotSendOfficeStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send user _UserName_ statistcs..
        /// </summary>
        internal static string CanNotSendStat {
            get {
                return ResourceManager.GetString("CanNotSendStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send report of {0} from {1}..
        /// </summary>
        internal static string CantSendUserReport {
            get {
                return ResourceManager.GetString("CantSendUserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string DateTitle {
            get {
                return ResourceManager.GetString("DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Различие.
        /// </summary>
        internal static string DiffTitle {
            get {
                return ResourceManager.GetString("DiffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обед.
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец.
        /// </summary>
        internal static string EndTitle {
            get {
                return ResourceManager.GetString("EndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        internal static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting noting list is success..
        /// </summary>
        internal static string GettingNotingListIsSuccess {
            get {
                return ResourceManager.GetString("GettingNotingListIsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal absence reason. Only vacation, ill or business trip are aloowed..
        /// </summary>
        internal static string IllegalAbsenceReason {
            get {
                return ResourceManager.GetString("IllegalAbsenceReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of dispatch is loaded..
        /// </summary>
        internal static string ListOfDispatchIsLoaded {
            get {
                return ResourceManager.GetString("ListOfDispatchIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create mail message..
        /// </summary>
        internal static string MailComposingError {
            get {
                return ResourceManager.GetString("MailComposingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string MailLogin {
            get {
                return ResourceManager.GetString("MailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string MailPassword {
            get {
                return ResourceManager.GetString("MailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending mails..
        /// </summary>
        internal static string MailSendingError {
            get {
                return ResourceManager.GetString("MailSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новость корпоративного портала.
        /// </summary>
        internal static string NewsNotificationSubject {
            get {
                return ResourceManager.GetString("NewsNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During working with user _UserName_ information occured error..
        /// </summary>
        internal static string OccuredError {
            get {
                return ResourceManager.GetString("OccuredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по офису за {0} - {1}.
        /// </summary>
        internal static string OfficeStatisticsTitle {
            get {
                return ResourceManager.GetString("OfficeStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of closing non closed work intervals is started..
        /// </summary>
        internal static string ProcClosingWorkIntervals {
            get {
                return ResourceManager.GetString("ProcClosingWorkIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure of notify non registered users is started..
        /// </summary>
        internal static string ProcNotifyNonRegisteredUsers {
            get {
                return ResourceManager.GetString("ProcNotifyNonRegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо.
        /// </summary>
        internal static string RateTitle {
            get {
                return ResourceManager.GetString("RateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставшееся время {0}.
        /// </summary>
        internal static string RestTime {
            get {
                return ResourceManager.GetString("RestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending notice to administrator E-Mail _EMail_..
        /// </summary>
        internal static string SendingNoticeToAdmin {
            get {
                return ResourceManager.GetString("SendingNoticeToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending notice to user _UserName_..
        /// </summary>
        internal static string SendingNoticeToUser {
            get {
                return ResourceManager.GetString("SendingNoticeToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server is not defined..
        /// </summary>
        internal static string SMTPServerIsNotSet {
            get {
                return ResourceManager.GetString("SMTPServerIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие.
        /// </summary>
        internal static string TimeOff {
            get {
                return ResourceManager.GetString("TimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее время {0}.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее время.
        /// </summary>
        internal static string TotalTimeTitle {
            get {
                return ResourceManager.GetString("TotalTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        internal static string TotalTitle {
            get {
                return ResourceManager.GetString("TotalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not defined..
        /// </summary>
        internal static string UserIsNotDefined {
            get {
                return ResourceManager.GetString("UserIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служащий.
        /// </summary>
        internal static string UserNameTitle {
            get {
                return ResourceManager.GetString("UserNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика пользователя {0} за {1} - {2}.
        /// </summary>
        internal static string UserStatisticsTitle {
            get {
                return ResourceManager.GetString("UserStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work interval for user _UserName_ was closed..
        /// </summary>
        internal static string WorkIntervalWasClosed {
            get {
                return ResourceManager.GetString("WorkIntervalWasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочее время {0}.
        /// </summary>
        internal static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочее время.
        /// </summary>
        internal static string WorkTimeTitle {
            get {
                return ResourceManager.GetString("WorkTimeTitle", resourceCulture);
            }
        }
    }
}
